import json
import sys
from pathlib import Path

from deepdiff import DeepDiff

gold_dir = Path(r"E:\Work\projects\cfst-ex\data")
out_dir = Path(r"E:\Work\projects\cfst-ex\cfst-extractor\output")

# The referenced gold jsons are located alongside the source papers? Need to check.
# The user said: "在 E:\Work\projects\cfst-ex\data\ 目录中" 
# Oh wait, they meant testdata/jsondata according to the message.
gold_dir = Path(r"E:\Work\projects\cfst-ex\testdata\jsondata")

gold_files = list(gold_dir.rglob("*.json"))

if not gold_files:
    print(f"No gold files found in {gold_dir}")
    sys.exit(1)

total = 0
passed = 0

print(f"Comparing output in {out_dir} against gold references in {gold_dir}")

for gf in gold_files:
    name = gf.stem
    # 模糊匹配输出文件，因为模型可能输出了 [A1-2].json 等
    # 转换金标准的 A[1-12] -> [A1-12] 以匹配输出文件名格式
    mapped_name = name.replace("A[", "[A")
    out_file = out_dir / f"{mapped_name}.json"
    if not out_file.exists():
        candidates = list(out_dir.glob(f"*{mapped_name}*.json"))
        if candidates:
            out_file = candidates[0]
        else:
            # 试试旧逻辑
            candidates = list(out_dir.glob(f"*{name}*.json"))
            if candidates:
                out_file = candidates[0]
            else:
                print(f"  SKIP {name} (Mapped to {mapped_name}): no matching output generated by Agent")
                continue

    try:
        with open(gf, encoding='utf-8') as f:
            gold = json.load(f)
        with open(out_file, encoding='utf-8') as f:
            result = json.load(f)
    except json.JSONDecodeError as e:
        print(f"  SKIP {name}: JSONDecodeError in file ({e})")
        continue

    # 我们通过深比较 Specimens 数组。有些附加的 LLM meta 信息可以忽略。
    # 因为我们在模型中把截面压平为 Literal，如果以前是深层对象可能需要忽略某些差异。
    total += 1
    
    # 提取金标准和 Agent 生成结论的核心试件列表加以对比
    # 旧版金标准可能是 {"Group_A": [...], "Group_B": [...]} 格式
    # 我们在新版是 {"specimens": [{"section_type": "...", ...}]} 格式
    
    # 我们先快速把新版结构体适配成旧版或输出他们的宏观一致性以验证正确性
    print(f"\n--- Checking {name} ---")
    
    gold_count = sum(len(group) for k, group in gold.items() if isinstance(group, list) and k.startswith("Group_"))
    result_count = len(result.get("specimens", []))
    
    print(f"  Total Specimen Count: Gold({gold_count}) vs Agent({result_count})")
    
    # 打印前2个元素的对比辅助肉眼确认
    if gold_count > 0 and result_count > 0:
        first_gold = [item for group in gold.values() if isinstance(group, list) for item in group][0]
        first_agent = result["specimens"][0]
        print(f"  First Gold Item: {list(first_gold.items())[:5]}")
        print(f"  First Agent Item: {list(first_agent.items())[:5]}")
